### ISSUE TITLE
instructions on how to build?

### ISSUE THREAD

**Issue by kevindevm** [dermow/TraXile#105]
title, i would like to mess arround with code and add pull request

**Comment by dermow** [comment]
Hi!

You should be able to just clone the repo and open the Project with Visual Studio 2019. Let me know if you encounter issues with that!

**Comment by kevindevm** [comment]
should i install something else? i got some warnings when trying to compile something about clickonce and log4net

**Comment by dermow** [comment]
You can ignore the clickonce warning. I played around with it and decided to use another plugin for setup creation. But you should have the log4net plugin installed, as it is used to write the logfile.

**Comment by dermow** [comment]
You can try to put the System.Data.SQLite.dll in your build directory (File should be included in Release.zip). For ClickOnce - just try to disable it. I will remove it with the next TraXile Release
