### ISSUE TITLE
[Suggestion] Minimize to System Tray

### ISSUE THREAD

**Issue by akeith997** [dermow/TraXile#109]
Is there any chance this feature could be added? I want to leave TraXile open but it bothers me having it on my taskbar (I know, lol) and would prefer if it just sat in my system tray. I know there's programs that would allow me to do this but if it was added natively I think many people would benefit.

**Comment by dermow** [comment]
Will be included in next release "1.1.5"

**Comment by dermow** [comment]
Resolved with Release 1.1.5 :-)
