### ISSUE TITLE
Error handing when selecting logfile path

### ISSUE THREAD

**Issue by dermow** [dermow/TraXile#130]

**Comment by dermow** [comment]
Fixed in 1.2.7

**Comment by LeGycz** [comment]
Having problems selecting logfile path after upgrading to Windows 11. 
Window automatically disappears 5 second after opening it.

**Comment by dermow** [comment]
Hi, could you try the following:

    1. Stop Traxile
    2. Delete the config file: \AppData\Roaming\TraXile\config.xml
    3. Try to start TraXile again

In the same directory, there should be a logfile - maybe there is some helpful information?

**Comment by LeGycz** [comment]
Thanks. Deleting file worked.

**Comment by dermow** [comment]
Fixed in current version
