### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by settonull** [dermow/TraXile#30]
Icon shows in taskbar for a second and then disappears.   There does not appear to be any log file, but happy to help debug however I can.

Windows 10 Pro /  i7-6700 / RTX 2080

**Comment by settonull** [comment]
First install ever, used 0.4.8.  And yes there were, thanks didn't think 
to look there...  it was an access exception, which made me realize that 
since I threw it in my program files folder I probably needed to run as 
admin, which worked, thanks!

Pretty cool, just fooling with it now.  Are you thinking of adding 
historical map tracking too like mapwatch?

Also, big feature request - as someone who plays a few characters each 
league - would be awesome if it could track by character (and still roll 
up to account too).

**Comment by dermow** [comment]
Ah ok, but good point. Already trying out to implement an installer and Updater tools for it.

On the right side, there are just live tracked activities (while TraXile open) at the moment.  Feature for historical tracking is already in work, but still struggling a bit with the time calculation there.

Need to check the logout thing - you can stop tracking manually with the stop button meanwhile.

Problem with character determination is, that it is not logged in Client.txt which char is active at the moment. You could use a custom tag for now.

Thanks a lot for you input, it really helps a lot!

**Comment by settonull** [comment]
Hmm, it actually doesn't show anything in the logs when I logged out.  
Also I see it doesn't generate a new area when I go from node to node in 
the mine, which is annoying.  And yeah, that's also pretty annoying that 
there is no character name in there, they do have the guild name 
though.  I wonder if they can be persuaded to add it and other useful 
things to the log.
