### ISSUE TITLE
custom auto-tagging system

### ISSUE THREAD

**Issue by Pegoth** [dermow/TraXile#65]
I think it would be nice to have the possibility to auto add custom tags based on regex. For example based on my #64 and #60 issues I would be able to create a custom tag instead of writing an issue (except maybe gwennen, as that was a bug).

Quick mock:
![mockup](https://user-images.githubusercontent.com/20708012/139312522-af4a3f1b-01a2-42d2-8dc9-61ff8c89caf4.png)

**Comment by dermow** [comment]
Performance still a problem - will close the Issue for now, sorry!
