### ISSUE TITLE
add leveling guide

### ISSUE THREAD

**Issue by dermow** [dermow/TraXile#75]

**Comment by dovry** [comment]
@dermow you should check out tenets of the [Unix Philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Origin). There is already a [tool](https://github.com/JusKillmeQik/PoE-Leveling-Guide) that does this for you

**Comment by dermow** [comment]
> @dermow you should check out tenets of the [Unix Philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Origin). There is already a [tool](https://github.com/JusKillmeQik/PoE-Leveling-Guide) that does this for you

Yeah you´re right. Was just an idea which I already discarded. Thanks for the feedback :)
