### ISSUE TITLE
Crash on startup - Bug

### ISSUE THREAD

**Issue by Weee-Gaming** [dermow/TraXile#77]
I am having crashes on startup. I had the application running until about yesterday or the day before and then possibly an update occurred and it broke.

I pulled some errors from the latest crash from Windows Event Viewer
1.
Application: TraXile.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException
   at TraXile.Main.ReadStatsCache()
   at TraXile.Main.Init()
   at TraXile.Main..ctor()
   at TraXile.Program.Main()

2.
Faulting application name: TraXile.exe, version: 0.7.4.0, time stamp: 0x617fbe00
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1288, time stamp: 0x3e55bd0b
Exception code: 0xe0434352
Fault offset: 0x0012b5b2
Faulting process id: 0x519c
Faulting application start time: 0x01d7cf82aacfb956
Faulting application path: C:\Users\freer\Desktop\dermow\TraXile\TraXile.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4050c9bc-4d51-427c-9e0f-4124682585e2
Faulting package full name: 
Faulting package-relative application ID: 

3.
Fault bucket 2172648112602723864, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: TraXile.exe
P2: 0.7.4.0
P3: 617fbe00
P4: TraXile
P5: 0.7.4.0
P6: 617fbe00
P7: 76
P8: 0
P9: System.IndexOutOfRangeException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2479.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2554.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2565.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER256B.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER257C.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_TraXile.exe_b49974404bcb43c0163053f7571f755843a3b8_84fdb29d_a7b78e9a-4e84-4798-a367-4080b3aaa7f1

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4050c9bc-4d51-427c-9e0f-4124682585e2
Report Status: 268435456
Hashed bucket: bf7a640e914a98855e26cbf27d9bb618
Cab Guid: 0

**Comment by dermow** [comment]
Hi!

Thanks for opening this issue :) Could you provide me the content of your stats.cache file? It is located in here:
<UserDirectory>\AppData\Roaming\TraXile

Best regards
Mow

**Comment by dermow** [comment]
Quick workaround would be to delete the content of Appdata/Roaming/TraXile which will cause TraXile to reload the logfile. But if you did a lot of custom tagging or manual pauses, this metadata will be lost unfortunately.

**Comment by Weee-Gaming** [comment]
stats.cache before I deleted the folder. Deleting seems to have fixed the issue, thanks!
last;1910463608
AreaChanges;43018
BaranStarted;38
BaranKilled;38
CampaignFinished;0
CatarinaTried;23
CatarinaKilled;23
TotalKilledCount;1790
DroxStarted;39
DroxKilled;39
EinharCaptures;788
ElderTried;60
ElderKilled;59
ExpeditionEncounters;1
ExpeditionEncounters_Rog;0
ExpeditionEncounters_Tujen;1
ExpeditionEncounters_Gwennen;0
ExpeditionEncounters_Dannig;0
HideoutTimeSec;84224
HighestLevel;100
HunterKilled;41
HunterStarted;41
LabsFinished;352
LabsStarted;710
LevelUps;217
MavenStarted;39
MavenKilled;38
TotalMapsDone;3122
TotalHeistsDone;22
ShaperTried;44
ShaperKilled;41
SimulacrumCleared;28
SimulacrumStarted;37
SirusStarted;38
SirusKilled;31
TemplesDone;79
TrialMasterStarted;4
TrialMasterKilled;3
TrialMasterTookReward;39
TrialMasterVictory;443
TrialMasterSuccess;482
VeritaniaKilled;40
VeritaniaStarted;40
HeistsFinished_Bunker;3
HeistsFinished_Laboratory;4
HeistsFinished_Mansion;1
HeistsFinished_Prohibited Library;2
HeistsFinished_Records Office;3
HeistsFinished_Repository;3
HeistsFinished_Smugglers Den;4
HeistsFinished_Tunnels;1
HeistsFinished_Underbelly;1
LabsCompleted_Unknown;8
LabsCompleted_The Labyrinth;3
LabsCompleted_The Merciless Labyrinth;1
LabsCompleted_The Cruel Labyrinth;1
LabsCompleted_Uber-Lab;140
LabsCompleted_Advanced Uber-Lab;197
MapsFinished_Academy;10
MapsFinished_Acid Caverns;4
MapsFinished_Alleyways;10
MapsFinished_Ancient City;89
MapsFinished_Arachnid Nest;6
MapsFinished_Arachnid Tomb;1
MapsFinished_Arcade;5
MapsFinished_Arena;27
MapsFinished_Arid Lake;7
MapsFinished_Armoury;7
MapsFinished_Arsenal;9
MapsFinished_Ashen Wood;59
MapsFinished_Atoll;176
MapsFinished_Barrows;6
MapsFinished_Basilica;4
MapsFinished_Bazaar;2
MapsFinished_Beach;9
MapsFinished_Belfry;5
MapsFinished_Bog;11
MapsFinished_Bone Crypt;6
MapsFinished_Bramble Valley;7
MapsFinished_Burial Chambers;30
MapsFinished_Cage;2
MapsFinished_Caldera;8
MapsFinished_Canyon;199
MapsFinished_Carcass;5
MapsFinished_Castle Ruins;8
MapsFinished_Cells;12
MapsFinished_Cemetery;11
MapsFinished_Channel;19
MapsFinished_Chateau;8
MapsFinished_City Square;17
MapsFinished_Cold River;6
MapsFinished_Colonnade;5
MapsFinished_Colosseum;6
MapsFinished_Conservatory;10
MapsFinished_Coral Ruins;3
MapsFinished_Core;8
MapsFinished_Courthouse;5
MapsFinished_Courtyard;180
MapsFinished_Coves;4
MapsFinished_Crater;6
MapsFinished_Crimson Temple;4
MapsFinished_Crimson Township;13
MapsFinished_Crystal Ore;53
MapsFinished_Cursed Crypt;9
MapsFinished_Dark Forest;5
MapsFinished_Defiled Cathedral;3
MapsFinished_Desert Spring;4
MapsFinished_Desert;5
MapsFinished_Dig;4
MapsFinished_Dry Sea;9
MapsFinished_Dunes;11
MapsFinished_Dungeon;10
MapsFinished_Estuary;13
MapsFinished_Excavation;10
MapsFinished_Factory;5
MapsFinished_Fields;9
MapsFinished_Flooded Mine;4
MapsFinished_Forbidden Woods;3
MapsFinished_Forge of the Phoenix;63
MapsFinished_Forking River;7
MapsFinished_Foundry;10
MapsFinished_Frozen Cabins;6
MapsFinished_Fungal Hollow;5
MapsFinished_Gardens;7
Ma

**Comment by Weee-Gaming** [comment]
That was the full content of the file exactly as I found it.

**Comment by dermow** [comment]
Fixed with 0.7.5
