### ISSUE TITLE
Most recent map not logged after completion

### ISSUE THREAD

**Issue by melink14** [dermow/TraXile#84]
Just started trying this out and it works well but noticed the last map I did was not tracked.

I didn't see this in the FAQ so thought I would post in case it was unexpected.

Details:
Tier 3 Core First time doing and at the end met Zana to unlock citadel.

**Comment by dermow** [comment]
Hi - thanks for the Report. Did you run the map with TraXile open? If not the most recent map will be finished when you start a new activity. Will add this to FAQ!
